### ISSUE TITLE
Getting network to work in the macOS VM

### ISSUE THREAD

**Issue by TimurEke** [kholia/OSX-KVM#34]
How to connect to a network in macOS? Somehow manage to configure a passthrough for the wireless adapter?

**Comment by kholia** [comment]
I haven't tried doing USB pass-through myself. However doing so using the virt-manager GUI should work easily.

https://wiki.archlinux.org/index.php/QEMU#Pass-through_host_USB_device seems relevant too.

To get the network working in the guest, follow https://github.com/kholia/OSX-KVM/blob/master/networking-qemu-kvm-howto.txt.

Please use descriptive titles instead of just saying "Network".
