### ISSUE TITLE
ITunes: This computer is already associated with an Apple ID.

### ISSUE THREAD

**Issue by kfirufk** [kholia/OSX-KVM#51]
Hi! :)

so.. everything works! sound.. video.. great!
now i want to play my apple music from itunes. when I try to play a song I get:

> This computer is already assosicated with an Apple ID.                        

> you can download past purchases on this computer with just one Apple ID every 90 days. You cannot associate this computer with a different Apple ID for 89 days.

I tried to google.. and all I could find is to use clover configuration to generate new smc string. where do I place it ? I even tried to install clover but the reboot doesn't really boot with clover :)

what's my next steps to investigate this issue further?

thanks!

**Comment by kholia** [comment]
I don't know anything about Clover. [This guide](http://www.nicksherlock.com/2016/11/using-clover-uefi-boot-with-sierra-on-proxmox/) talks about using OVMF + Clover with QEMU/KVM.

Try getting help on the various Hackintosh forums (InsanelyMac, tonymacx86.com). [This page](https://www.reddit.com/r/hackintosh/comments/59kpu2/this_computer_is_already_associated_with_an_apple/) also seems relevant.

**Comment by kfirufk** [comment]
ahhm.. why was this issue closed ? the issue wasn't resolved.. or anything. I don't know how to replace your chameleon configuration with clover.. and I have no clue how to solve this.

**Comment by kholia** [comment]
Clover is not used by this project (it is out of scope for this project). I can't provide support for it. See the links I posted, they might lead to a solution.

**Comment by kfirufk** [comment]
I guess I wasn't explaining myself properly. I don't use clover... I use your project.. which seems to use chameleon configuration. all I said is that when I googled I found work-arounds that use clover, none for your configuration.

**Comment by kholia** [comment]
I got a tip from another user saying, download a Chameleon wizard such as Chameleon Wizard or Champlist in order to generate a usable SMBios.plist. This file goes into /Extras and can be used to assign a reasonable serial number to your virtual Mac. Generating this file sometimes fixes software incompatibilities that occur when the software can't determine what Apple hardware it is running on.

Maybe this tip can fix the current issue? I can't confirm the fix because I don't use iTunes (or iMessage).
