### ISSUE TITLE
Can't get tap networking to work on Arch Linux

### ISSUE THREAD

**Issue by C0rn3j** [kholia/OSX-KVM#79]
I'm using:

* Arch Linux (4.11.9)
* El Capitan image 
* Networking relevant parts from boot-macOS.sh script look like this,

```
# -netdev user,id=net0 -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \ # this works, but slowly!
-netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \
```

I can't for the love of god get the tap networking thing to work. 

I tried these commands - they executed successfully.

```
sudo ip tuntap add dev tap0 mode tap
sudo ip link set tap0 up promisc on
sudo brctl addif virbr0 tap0
```

But adding the tap line networking line gives me no network when I boot the virtual through the script.

This is output from `ip a` on host,

```
$ ip a             
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 78:24:af:37:08:9b brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.100/24 brd 192.168.1.255 scope global eno1
       valid_lft forever preferred_lft forever
    inet 192.168.1.125/24 brd 192.168.1.255 scope global secondary eno1
       valid_lft forever preferred_lft forever
    inet6 fde6:2d3b:2625::751/128 scope global 
       valid_lft forever preferred_lft forever
    inet6 fde6:2d3b:2625:0:3ca3:3ac9:94f0:c39e/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fde6:2d3b:2625:0:5244:1ac9:d3fa:d129/64 scope global noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::3937:54c0:a79d:e6c9/64 scope link 
       valid_lft forever preferred_lft forever
3: virbr1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:b9:a3:6c brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.1/24 brd 192.168.100.255 scope global virbr1
       valid_lft forever preferred_lft forever
4: virbr1-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr1 state DOWN group default qlen 1000
    link/ether 52:54:00:b9:a3:6c brd ff:ff:ff:ff:ff:ff
5: virbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 02:70:19:6e:96:45 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
6: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:d4:49:4f brd ff:ff:ff:ff:ff:ff
12: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master virbr0 state UNKNOWN group default qlen 1000
    link/ether fe:54:00:ab:19:04 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:feab:1904/64 scope link 
       valid_lft forever preferred_lft forever
20: tap0: <NO-CARRIER,BROADCAST,MULTICAST,PROMISC,UP> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 02:70:19:6e:96:45 brd ff:ff:ff:ff:ff:ff
```

Any help/hints welcome.

**Comment by kholia** [comment]
I don't have the expertise to debug such networking issues (which might be specific to Linux distribution / local setup). Perhaps consult general purpose Linux forums instead?

**Comment by Shoaloak** [comment]
Had the same(ish) problems on Gentoo, this solved it for me:

- **install libvirtd**, it's required for virtmanager, **enable/start** it's **service / daemon**
- **install virtmanager**, as stated in "networking-qemu-kvm-howto.txt"
- When starting virtmanager, connect to QEMU/KVM and check the tab virtual networks, *default* or virbr0 _should_ be active.

If you are like me however, it isn't active. When trying to start it I ran into alot of errors, e.g.:
> Error starting network 'default': internal error: Failed to apply firewall rules /sbin/iptables -w --table nat --insert POSTROUTING --source 192.168.122.0/24 '!' --destination 192.168.122.0/24 --jump MASQUERADE: iptables v1.4.21: can't initialize iptables table `nat': Table does not exist (do you need to insmod?) Perhaps iptables or your kernel needs to be upgraded

> bla bla bla sbin/iptables -w --table nat --insert POSTROUTING --source 192.168.122.0/24 ! --destination 192.168.122.0/24 --jump MASQUERADE failed bla bla bla

This can be solved by installing firewalld, which has the **necessary dependencies** (IIRC dnsmasq, ebtables, ipset, etc).
After install, **enable/start firewalld**, which **modprobes ip_table, iptable_nat, ebtables, etc** and you should be able to activate the default virtual network. Firewalld does require some set Linux kernel configuration items, i think Arch solves this automatically, but otherwise Gentoo wiki is an excellent resource:
https://wiki.gentoo.org/wiki/Iptables
https://wiki.gentoo.org/wiki/IPSet
(This does mean that after installation, a reboot is a good idea because of new kernel modules)

- After all this, run the 3 commands specified in "networking-qemu-kvm-howto.txt", make sure your boot-macOS.sh contains `-netdev tap,id=net0,ifname=tap0,script=no,downscript=no -device vmxnet3,netdev=net0,id=net0,mac=52:54:00:c9:18:27 \
` (vmxnet3 = newer = better)
- ???
- Profit, well er... I mean network connection ;)

Sources:
https://bbs.archlinux.org/viewtopic.php?id=198744
https://www.redhat.com/archives/libvirt-users/2013-November/msg00146.html
https://bbs.archlinux.org/viewtopic.php?id=160219

**Comment by C0rn3j** [comment]
I actually don't have issues with the virtual network being active, I think I solved it before since I have many working non-macOS VMs.

When I kill the VM the terminal spits these lines out.. not sure if they're relevant. 

./boot-macOS.sh: line 32: -netdev: command not found
./boot-macOS.sh: line 36: -monitor: command not found

Would you care posting your whole boot script on some paste service? Use mine if you want. https://paste.c0rn3j.com/

**Comment by Shoaloak** [comment]
This means bash tries to interpret your -netdev / whateff as shell command, are there comments separating it from the rest of the qemu flags?

**Comment by kholia** [comment]
@C0rn3j @Shoaloak 

Paste the relevant information in here instead of using external links which have a tendency to disappear. As a matter of fact, `https://paste.c0rn3j.com` appears to be down at the moment.

**Comment by C0rn3j** [comment]
I am aware of external links, am fully expecting to post the solution here instead of a link to solution, I just didn't want to uselessly clutter this page with full scripts.

**Comment by kholia** [comment]
I prefer having all the relevant information on this page. Like I said, `https://paste.c0rn3j.com` is down, and other readers of this page are going to have trouble following the conversation. Think from the perspective of other readers to understand what I am saying.

**Comment by C0rn3j** [comment]
>are there comments separating it from the rest of the qemu flags?

Looks like this was one of my issues. Networking still doesn't work but I can at least see that there's an adapter in ifconfig. Will try messing with this further and I'll report back.

**Comment by C0rn3j** [comment]
And my second issue was that I didn't execute the tap commands again after a reboot. Networking now works, thanks!

**Comment by Shoaloak** [comment]
> EDIT3: Btw @Shoaloak your config has an useless \ at the last line. I was told elsewhere that this can cause problems in some situations.

Thanks for the heads up, will remove.
